backend:
  name: github
  repo: gasakawa/blog
  branch: master
  site_domain: gasakawa.com

publish_mode: editorial_workflow
media_folder: 'static/assets/img'
public_folder: 'assets/img'

collections:
  - name: 'posts' # Used in routes, e.g., /admin/collections/blog
    label: 'Posts' # Used in the UI
    folder: 'posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: 'image', name: 'image', widget: 'image' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'select',
          options: ['CSS', 'JS', 'HTML', 'Java', 'Cloud', 'Misc', 'Basket'],
        }
      - {
          label: 'Background',
          name: 'background',
          widget: 'select',
          options:
            [
              { label: 'Red - Basket', value: '#B31917' },
              { label: 'Blue - CSS', value: '#3b9ce5' },
              { label: 'Yellow - JS', value: '#F0D91D' },
              { label: 'Orange - HTML', value: '#EB7728' },
              { label: 'Red - Java', value: '#CA1F22' },
              { label: 'Blue - Cloud', value: '#4081ED' },
              { label: 'Green - Misc', value: '#7AAB13' },
              { label: 'Mustard - Dev', value: '#FCB005' },
            ],
        }
      - { label: 'Keywords', name: 'keywords', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
