export const posts = [
  {
    slug: 'fundamentos-de-javascript-bind-call-apply',
    category: 'backend',
    date: '2022-07-19',
    title: 'Fundamentos de Javascript - Bind, Call e Apply',
    excerpt: 'CO que são os métodos bind, call e apply em funções dentro do javascript',
    tags: 'javascript',
  },
  {
    slug: 'o-que-e-document-flow',
    category: 'frontend',
    date: '2021-02-03',
    title: 'O que é document flow?',
    excerpt: 'Um resumo sobre o document flow em documentos HTML',
    tags: 'html',
  },
  {
    slug: 'otimizando-imagens-com-nodejs',
    category: 'backend',
    date: '2020-09-18',
    title: 'Otimizando imagens com NodeJS',
    excerpt: 'Como otimizar imagens utilizando a lib sharp',
    tags: 'javascript,nodejs',
  },
  {
    slug: 'desestruturacao-de-objetos-e-arrays-em-js',
    category: 'frontend,backend',
    date: '2020-05-19',
    title: 'Desestruturação de objetos e arrays em Javascript',
    excerpt: 'Como usar a desestruturação em Javascript',
    tags: 'javascript',
  },
  {
    slug: 'salvando-alteracoes-locais-com-o-devtools-do-browser',
    category: 'frontend',
    date: '2020-05-13',
    title: 'Salvando alterações locais com o DevTools do browser',
    excerpt: 'Como salvar mudanças no CSS ou HTML direto na sua máquina usando DevTools',
  },
  {
    slug: 'meu-primeiro-post',
    category: 'geral',
    date: '2020-04-27',
    title: 'Meu primeiro post',
    excerpt: 'Seja bem-vindo',
  },
];
